runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app

#[START env]
env_variables:
    CLOUD_STORAGE_BUCKET: khet-online-storage
#[END env]

skip_files:
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/env/.*$
- ^(.*/)?\..*$