runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 2

handlers:
- url: /static/.*
  static_dir: static

- url: /.*
  script: main.app

#[START env]
env_variables:
    CLOUD_STORAGE_BUCKET: khet-online-storage
#[END env]

skip_files:
- ^(.*/)?.*\.py[co]$

